name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_firmware:
    name: Build Firmware Example
    runs-on: ubuntu-latest
    container: espressif/idf:release-v5.5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build Firmware
        shell: bash
        working-directory: test_apps/build_test
        run: |
          . $IDF_PATH/export.sh
          idf.py build

  host_tests:
    name: Host Tests
    runs-on: ubuntu-latest
    container: espressif/idf:release-v5.5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build all tests
        shell: bash
        working-directory: host_test
        run: |
          . $IDF_PATH/export.sh
          cmake -B build -S .
          cmake --build build --target build_all_tests

      - name: Run tests
        shell: bash
        working-directory: host_test/build
        run: |
          . $IDF_PATH/export.sh
          ctest --output-on-failure --output-junit test_results.xml

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: host-test-results
          path: host_test/build/test_results.xml
